# -*- coding: utf-8 -*-
"""0417Download_sitting_pose_unsplash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hi5erQRFHS_9UbMlgcL9m6OTh4IXw0xp
"""

# # 從第一頁開始，一頁30張圖
# import json
# from urllib.request import urlopen

# imgs_url = []
# # 改page頁數 看要從第幾頁開始
# page = 1

# while True:
#   count = 0
#   url = "https://unsplash.com/napi/search/photos?query=sitting&per_page=30&page=" + str(page) + "&xp="
#   response = urlopen(url)
#   index = json.load(response)
#   pics = index["results"]
#   if not pics:
#     print("應該是最後一頁")
#     break
#   print("第"+ str(page) +"頁")
#   for p in pics:
#       img_index = p["links"]
#       img = img_index["download"]
#       imgs_url.append(img)
#       print(img)
#       count += 1
#   print("這頁有幾張:", count)
#   page += 1
# # len(imgs_url)

# 從第一頁開始，一頁30張圖
import json
from urllib.request import urlopen
import math
imgs_url = []
# 改page頁數 看要從第幾頁開始，一頁30張
p = int(input("請輸入從第幾張開始下載："))
# print(type(p))
page = math.ceil(p / 30)
# print("從第", page , "頁開始")
r = int(input("請輸入從第幾張結束下載："))
rg = math.ceil(r / 30)
rg = rg - page + 1
for i in range(rg):
  count = 0
  url = "https://unsplash.com/napi/search/photos?query=sitting&per_page=30&page=" + str(page) + "&xp="
  response = urlopen(url)
  index = json.load(response)
  pics = index["results"]
  if not pics:
    print("應該是最後一頁")
    break
  print("第"+ str(page) +"頁")
  for pic in pics:
      img_index = pic["links"]
      img = img_index["download"]
      imgs_url.append(img)
      print(img)
      count += 1
  print("這頁有幾張:", count)
  page += 1
# len(imgs_url)
print(p)

# 利用上面的imgs_url = []下載圖片
import os
import shutil
import requests

# 下載檔案api:https://titangene.github.io/article/python-crawler-note.html
# base, D:\tt_group_total_pics\sitting_pose_5130_plus 存檔路徑

base = "sitting_pose"
if not os.path.exists(base):
  os.makedirs(base)
for i, iurl in enumerate(imgs_url):
  iresponse = requests.get(iurl, stream=True, verify=False)
  #fn = file_name
  # str(i + p) , i:為enumerate的index 從0開始, p:為上述的input第幾張開始命名
  fn = os.path.join(base, str(i+p) + "." + "jpg")
  with open(fn, "wb") as f:
    shutil.copyfileobj(iresponse.raw, f)